# Config file for automatic testing at travis-ci.org
dist: trusty
language: python
python:
  - 3.6
  - 3.5
  - 3.4

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required

# Command to install dependencies
install: pip install -U tox-travis codecov

after_success: codecov

# Command to run tests
script: tox

deploy:

  # Automatically deploy releases to PyPI for each tagged commit
  # Assuming you have installed the travis-ci CLI tool, after you
  # create the Github repo and add it to Travis, run the
  # following command to finish PyPI deployment setup:
  # $ travis encrypt MY_PYPI_PASSWORD
  # and then copy the (really long) encrypted password as shown.
  - provider: pypi
    distributions: sdist bdist_wheel
    user: mit_dai_lab
    password:
      secure: PLEASE_REPLACE_ME
    on:
      tags: true
      repo: DAI-Lab/pyreal
      python: 3.6

  # Automatically build and deploy documentation to GitHub Pages after every
  # commit
  # Follow the instructions at https://docs.travis-ci.com/user/deployment/pages/
  # to setup a personal deployment token and then provide it as a secure
  # environment variable at https://travis-ci.org/DAI-Lab/explanation-toolkit/settings
  - provider: pages
    skip-cleanup: true
    github-token: "$GITHUB_TOKEN"
    keep-history: true
    local-dir: docs/_build/html
    target-branch: gh-pages
    on:
      branch: master
      python: 3.6
